### ISSUE TITLE
Exit used instead of SetError

### ISSUE THREAD

**Issue by timcrid** [xLinkOut/telegram-udf-autoit#10]
In the `_InitBot()` function, you call Exit instead of SetError. Is this the wanted behaviour?
It's really confusing when the script exits without any message, except a ConsoleWrite.
Especially in a compiled script you don't know why the script ends.

btw: nice work 👍

**Comment by xLinkOut** [comment]
The script use Exit function because without a valid token, the code is useless. But you're right, maybe SetError is more appropriate. If you want to change and make a PR, feel free to contribute, or I can implement this ASAP. Thanks 😄

**Comment by xLinkOut** [comment]
Hi @timcrid! I have implemented your solution about `SetError` instead of a brutal `Exit` and added instructions on how to properly use this feature in a script. Thank you! 👍
