### ISSUE TITLE
Fix for sending multiple rows in _CreateInlineKeyboard()

### ISSUE THREAD

**Issue by RazTK** [xLinkOut/telegram-udf-autoit#11]
Right now it's broken. Here's a fix:
Line 146: `ElseIf(StringRight($jsonKeyboard,2) = '],') Then`
Line 147: `$jsonKeyboard &= '[{"text":"' & $Keyboard[$i] & '",'`
Line 150: `$jsonKeyboard &= '],'`

**Comment by xLinkOut** [comment]
Hi @RazTK! Thank you for reporting this bug, it's fixed now! 👍
