### ISSUE TITLE
Fix for _answerCallbackQuery()

### ISSUE THREAD

**Issue by RazTK** [xLinkOut/telegram-udf-autoit#12]
Broken right now.
Change the following lines:
Line 517 to: `Func _answerCallbackQuery($CallbackID,$Text = '',$cusURL = '',$ShowAlert = False,$CacheTime = '')`
Line 518 to: `Local $Query = $URL & "/answerCallbackQuery?callback_query_id=" & $CallbackID`
Line 520 to: `If $cusURL <> '' Then $Query &= "&url=" & $cusURL`

**Comment by xLinkOut** [comment]
Hi @RazTK! This bug is fixed now, thank you for your contribution!
