### ISSUE TITLE
Incorrect text decoding for channel messages

### ISSUE THREAD

**Issue by brain4tech** [xLinkOut/telegram-udf-autoit#13]
No text in $msgData[5] when an admin sent a message in a channel while looping _Pollling.
_getUpdates recognizes the text of the message.

_getUpdates output message:
![_getUpdates Output](https://user-images.githubusercontent.com/59681472/72046629-1de35e00-32b9-11ea-89be-85f0a15c147c.png)

$msgData from _Polling:
![$msgData from _Pollig Output](https://user-images.githubusercontent.com/59681472/72046278-58003000-32b8-11ea-89e5-090693ec07ac.png)

I looked into the Telegram UDF and checked that the array index are correct.I saw that behind the line for the text it sais ";[5] = Text (eventually)" Does that "eventually" has something to do with my issue?

Thanks!

**Comment by xLinkOut** [comment]
Probably this happens due to the json parser. Definitively `__MsgDecode` need a rework, thanks for reporting, I'll check this out soon! If you came up with a solution, comment here or make a pull request!

**Comment by brain4tech** [comment]
**Found the solution!!!**

It`s in line 1052. The JSON tag <code>[message]</code> should be <code>[channel_post]</code>

Tell me if you need a detailed explanation!

**Comment by xLinkOut** [comment]
Hey! Thanks for your help! I've fixed and tested this, download the newer version of `Telegram.au3` and let me know here if it works! Look that I've also changed the order of title, text ecc in msgData, check the source.

**Comment by brain4tech** [comment]
Hey! Thank you for the new version! It works perfectly!
Thanks for making this useful UDF! It is so useful for my project!

**Comment by xLinkOut** [comment]
Nice! Oh thanks, happy to hear that my work is useful to you! Keep buildining awesome stuffs!
