### ISSUE TITLE
i got error messege when use func polling

### ISSUE THREAD

**Issue by thegopza** [xLinkOut/telegram-udf-autoit#19]
telegram-udf-autoit-master\src\Telegram.au3" (794) : ==> Subscript used on non-accessible variable.:
$OFFSET = $msgData[0] + 1
$OFFSET = $msgData^ ERROR
can someone help

thank for reply

**Comment by xLinkOut** [comment]
Hi, as explained in #18, this kind of errors are now fixed, deprecating the `__MsgDecode` function and the `$msgData[$i]` approach. If you want, give a try to the new version of the library.
