### ISSUE TITLE
username or first_name 

### ISSUE THREAD

**Issue by nengoxx** [xLinkOut/telegram-udf-autoit#2]
First of all awesome work, saved me some time
[Telegram UDF.zip](https://github.com/xLinkOut/telegram-udf-autoit/files/788944/Telegram.UDF.zip)

I had to change the code to make it work for me, in the _JSONDecode($) function when looking for the name(for me at least) the "username" field wasn't there and it was named "first_name" instead, you check if the username is blank after the first attempt but I had to change: "$dataArray[3]" which is the text for "$dataArray[1]", also it stored the value in $dataArray[3], I changed to $dataArray[1]. I suppose the whole thing may be some api change or just me trying it on a private chat, but I attached my file for you to see, just changed those 2 lines and it seems to work well.

**Comment by chechelaky** [comment]
Greetings!

I see you json function...

See this: https://github.com/chechelaky/AutoIt/blob/master/JSMN.au3

I use this UDF more over 4 years, not 100%, but is 99.99% good!

Maybe help you.

Tip: use "Scripting.Dictionary".

Best regards

**Comment by xLinkOut** [comment]
Thank you @nengoxx for report this problem. I'll check this.
Thanks also to @chechelaky , probably I'll implement that udf to decode json response and create custom array with information. If you need urgent solution, check the other version https://github.com/xLinkOut/telegram-udf-php I just updated the JSONDecode function with other params. In the next days I'll update also this version.

**Comment by volond1975** [comment]
December 4, 2016

Introducing Bot API 2.3.1, a nifty little update that will give you more control over how your bot gets its updates.
Use allowed_updates in setWebhook and getUpdates to selectively subscribe to updates of a certain type. Among other things, this allows you to stop getting updates about new posts in channels where your bot is an admin.

**Comment by xLinkOut** [comment]
Hi all. I've released v3.0 which implement a good JSON parser and a new, improved MsgDecode function. Now there is no more issue with username and first_name. Thanks for support 😊
