### ISSUE TITLE
_SendMsg with Url Encode

### ISSUE THREAD

**Issue by nicolasegp** [xLinkOut/telegram-udf-autoit#3]
hi! I love this project

Wanted to propose an improvement in the _SendMsg function
If I want to make a line break I have to put **`%0A`** that equals **`\n`**

Could you integrate such a function?
Since I work in the Spanish language and we have accents and characters that must be encoded
Ex. **`á é í ó ú ñ`** -> **`%C3%A1 %C3%A9 %C3%AD %C3%B3 %C3%BA %C3%B1`**`

have a nice day! :v:

**Comment by nicolasegp** [comment]
It was my file problem
Used another encoding. With UTF-8 works well including emojis

Sorry for the issues xD

**Comment by xLinkOut** [comment]
Sorry for this late reply, I was working on other things away from GitHub. Better this way, for your problem :D If you want to contribute to this repo, create a pull request or contact me! I'll appreciate 😄
