### ISSUE TITLE
line-break doesn't work

### ISSUE THREAD

**Issue by nicolasegp** [xLinkOut/telegram-udf-autoit#4]
Hi, when I try to use **`@CRLF`** it doesn't work when I send it to telegram, I have to use **`%0D%0A`** or only **`%0A`** directly in the String to generate the line break.

You could create a constant or encode the text string to be compatible with URL

---

https://www.autoitscript.com/forum/topic/144032-url-encoding/

```Autoit
#include <String.au3>
#include <Array.au3>

Func _urlencode($string)
    $string = StringSplit($string, "")
    For $i=1 To $string[0]
        If AscW($string[$i]) < 48 Or AscW($string[$i]) > 122 Then
            $string[$i] = "%"&_StringToHex($string[$i])
        EndIf
    Next
    $string = _ArrayToString($string, "", 1)
    Return $string
EndFunc

ConsoleWrite(_urlencode("Test"&@CRLF&"Test"))
```

**Result:**
```
Test%0D%0ATest
```

**Comment by xLinkOut** [comment]
Hi! Thanks for this snippet. I've read the other issue too. I'm currently working on a custom JSON Encoder/Decoder in AutoIt to properly decode Telegram response, because as you can see now I use string tricks and it's not a good way. ASAP I'll update this repo.

**Comment by nicolasegp** [comment]
It's sad that Autoit doesn't have a native function for JSON
hmmm, if you use any UDF? or using RegExp? 😕

**Comment by xLinkOut** [comment]
Yea, I know, it's sad. But, after a lot of not-working json parser, I think I've found a good UDF here on GitHub, i'm testing it now.

**Comment by xLinkOut** [comment]
Hi! Try the new version of the library please, I've include a constant $BOT_CRLF, already encoded, for line break in message. Let me know if it works well, so I can close this issue.

**Comment by sergeyFlakon** [comment]
It does work! Thanks
"first line" & $BOT_CRLF & "second line"

**Comment by xLinkOut** [comment]
Nice! Closed :)
