### ISSUE TITLE
Support for Callbacks

### ISSUE THREAD

**Issue by nicolasegp** [xLinkOut/telegram-udf-autoit#5]
If you try to use **reply_markup** with **"inline_keyboard"** it will give you an error in the **_JSONDecode** function.

How could I use inline_keyboard and get callbacks without problems?

**Comment by xLinkOut** [comment]
Hi again! Now MsgDecode (old JSONDecode function) can return a valid callback information (in array format) but I'm working on a CreateInlineKeyboard function to make simple create custom inline keyboards directly in the code. You can always use an already JSON encoded inline keyboard and pass it to the send function as $ReplyMarkup parameter. Let me know.

**Comment by xLinkOut** [comment]
There is now full support to receive callback and answer to it. Also, with _CreateKeyboard and _CreateInlineKeyboard functions you can easily create custom keyboard to pass to reply_markup.
