### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DIx37** [xLinkOut/telegram-udf-autoit#6]
No "EndFunc"
Func _CreateInlineKeyboard(ByRef $Keyboard)
    Local $jsonKeyboard = '{"inline_keyboard":[['
    Return $jsonKeyboard
**EndFunc**

#include <String.au3>
740             $string[$i] = "%"&**_StringToHex**($string[$i])

**Comment by xLinkOut** [comment]
Fixed! Thanks for report.

**Comment by DIx37** [comment]
Func __MsgDecode in Group:
> Error: Error in expression.

Delete "**,**" 782 Line.
```
782            Json_Get($Json,'[result][0][message][chat][title]'), _ ;[6] = Group Name
782            Json_Get($Json,'[result][0][message][chat][title]') _ ;[6] = Group Name
```

**Comment by xLinkOut** [comment]
Fixed, thanks!
