### ISSUE TITLE
Edited message causes "$Offset = $msgData[0] + 1 $Offset = $msgData^ ERROR"

### ISSUE THREAD

**Issue by sergeyFlakon** [xLinkOut/telegram-udf-autoit#8]
Send message to bot
Edit it

Script will stop and won't run for this while this edited message exists
Always fail with:
Telegram.au3" (94) : ==> Subscript used on non-accessible variable.:
$Offset = $msgData[0] + 1
$Offset = $msgData^ ERROR

**Comment by sergeyFlakon** [comment]
just message:

> "message":{"message_id":20,"from":{"id":515802,"is_bot":false,"first_name":"\u0421\u0435\u0440\u0433\u0435\u0439","last_name":"\u041c\u043e\u0441\u0442","username":"Sergey_mOSt","language_code":"en-US"},"chat":{"id":515802,"first_name":"\u0421\u0435\u0440\u0433\u0435\u0439","last_name":"\u041c\u043e\u0441\u0442","username":"Sergey_mOSt","type":"private"},"date":1519741169,"text":"online"}},{"update_id":387811338,

edited message:

> "edited_message":{"message_id":18,"from":{"id":515802,"is_bot":false,"first_name":"\u0421\u0435\u0440\u0433\u0435\u0439","last_name":"\u041c\u043e\u0441\u0442","username":"Sergey_mOSt","language_code":"en-US"},"chat":{"id":515802,"first_name":"\u0421\u0435\u0440\u0433\u0435\u0439","last_name":"\u041c\u043e\u0441\u0442","username":"Sergey_mOSt","type":"private"},"date":1519740810,"edit_date":1519740816,"text":"online @ haha"}},{"update_id":387811337,

**Comment by sergeyFlakon** [comment]
Seems like adding this under ;@PRIVATE CHAT MESSAGE block solves the issue:

```
;@EDITED PRIVATE CHAT MESSAGE
    ElseIf(Json_Get($Json,'[result][0][edited_message][chat][type]') = 'private') Then
        Local $msgData[10] = [ _
            Json_Get($Json,'[result][0][update_id]'), _ ;[0] = Offset
            Json_Get($Json,'[result][0][edited_message][message_id]'), _ ;[1] = Message ID
            Json_Get($Json,'[result][0][edited_message][from][id]'), _ ;[2] = Chat ID
            Json_Get($Json,'[result][0][edited_message][from][username]'), _ ;[3] = Username
            Json_Get($Json,'[result][0][edited_message][from][first_name]') _ ;[4] = Firstname
        ]

        If(Json_Get($Json,'[result][0][edited_message][text]')) Then $msgData[5] = Json_Get($Json,'[result][0][edited_message][text]') ;[5] = Text (eventually)

        ;Insert media recognition here

        Return $msgData
```

**Comment by sergeyFlakon** [comment]
Feels like edited group chat and channel message will cause same issue

**Comment by xLinkOut** [comment]
Seems that an edited message generate a different JSON that my previous decode function can't parse. With your code now there is a parser for the edited messages, it works. Now I've to do the same with group and channel. Thanks for report and for the fix!

**Comment by xLinkOut** [comment]
Ok seems that I've fixed also group and channel issue. Need to add media recognition for all this new parser but at least it doesn't crash. Commit and push soon. Would you want credits in readme file for the fix? :)

**Comment by sergeyFlakon** [comment]
@xLinkOut Yeah, leave it somewhere as "Sergey Flakon" :)
Thanks!

**Comment by xLinkOut** [comment]
Perfect! Thank you again! :)

**Comment by khanh3t** [comment]
Hi, @xLinkOut . I think this issue can't use @sergeyFlakon code when msg edit in group chat

> {"ok":true,"result":[{"update_id":479705694,
"edited_message":{"message_id":316,"from":{"id":711600853,"is_bot":false,"first_name":"Xuan Khanh","last_name":"Trinh","username":"khanhtx","language_code":"vi"},"chat":{"id":-1001294028923,"title":"GOLD Notification","type":"supergroup"},"date":1584712248,"edit_date":1584977580,"text":"\ud83d\udca1Gi\u1ea3i th\u00edch c\u00e1c k\u00fd hi\u1ec7u:\n\n * GOLD USD : Gi\u00e1 v\u00e0ng th\u1ebf gi\u1edbi\n * GOLD VND : Gi\u00e1 v\u00e0ng th\u1ebf gi\u1edbi quy \u0111\u1ed5i ra VND\n\n * MV SJC : Gi\u00e1 mua v\u00e0o SJC\n * BR SJC : Gi\u00e1 b\u00e1n ra SJC\n\n * MV 24K : Gi\u00e1 mua v\u00e0o 9999\n * BR 24K : Gi\u00e1 mua v\u00e0o 9999\n\n * Ch\u00eanh GDMB : Ch\u00eanh gi\u1eefa b\u00e1n ra mua v\u00e0o SJC/9999\n * Ch\u00eanh GVND : Ch\u00eanh gi\u1eefa SJC/9999 v\u1edbi v\u00e0ng th\u1ebf gi\u1edbi\n \n \ud83d\udca1H\u1ec7 th\u1ed1ng t\u1ef1 \u0111\u1ed9ng th\u00f4ng b\u00e1o khi:\n \n * Gi\u00e1 v\u00e0ng th\u1ebf gi\u1edbi bi\u1ebfn \u0111\u1ed9ng > 0.5%\n * Gi\u00e1 v\u00e0ng SJC/9999 c\u00f3 bi\u1ebfn \u0111\u1ed9ng\n * B\u1ea1n c\u00f3 th\u1ec3 nh\u1eafn tin ri\u00eang cho nick BOT \u0111\u1ec3 ki\u1ec3m tra gi\u00e1 t\u1ea1i th\u1eddi \u0111i\u1ec3m hi\u1ec7n t\u1ea1i"}}]}

Subscript used on non-accessible variable.:
$OFFSET = $msgData[0] + 1
$OFFSET = $msgData^ ERROR
