### ISSUE TITLE
ran test sample failed for sending image/audio/video/photo function

### ISSUE THREAD

**Issue by paynepeng** [xLinkOut/telegram-udf-autoit#9]
I downloaded telegram UDF files from github.  I ran the sample code and most telegram functions failed.
Only the "send message, location, contact" working well , the others such as send audio/image/video.... all failed.
I don't know what's wrong. Could some give me suggestion?
note: I used autoit v3.3.14.5

**Comment by sergeyFlakon** [comment]
Hey, what is output for uncompiled script?

**Comment by xLinkOut** [comment]
All _SendMedia functions required a valid file path as second argument. For example:
```autoit
ConsoleWrite("Sending photo..." & _SendPhoto($ChatID,'C:\image.jpg',"This is a photo.") & " ...Done!" & @CRLF)
```
"C:\image.jpg" is a jpg file stored in C:\. In your case the functions return error because those file didn't exists.

Maybe I'll put some test files like jpg/mp4/ogg directly into test folder. Thanks for report! Check this later.

**Comment by paynepeng** [comment]
Thanks.   I have noticed the second parameter for file location. I put image.jpg/audio.mp3 into c:\  but the uncompiled script still console output "fail"

my code:
=======
ConsoleWrite("Test _SendPhoto    -> "  & @TAB & _SendPhoto($ChatID,"c:\image.jpg","Test SendPhoto") & @CRLF)
ConsoleWrite("Test _SendAudio    -> "  & @TAB & _SendAudio($ChatID,"c:\audio.mp3","Test SendAudio") & @CRLF)

console show result as below:
===================
Test _GetUpdates   -> 	{"ok":true,"result":[]}
Test _SendPhoto    -> 	False
Test _SendAudio    -> 	False
{"ok":true,"result":[]}


Attache screenshot show my file location is c:\ 
======
![filelocation](https://user-images.githubusercontent.com/37009382/44268942-9e896080-a265-11e8-8703-9643051b479a.gif)

**Comment by sergeyFlakon** [comment]
Will it work if you'll use this:
_SendPhoto("123456","C:\image.jpg")
where 123456 should be replaced with your telegram ID

To check your ID you can use one of these bots:
@MyTelegramID_bot
@GetMyIDBot
@my_id_bot

Also you have to add your bot to contacts on this account to see message arriving

**Comment by paynepeng** [comment]
1 my id can use 3 bots you assigned. (see attached screenshot of my id)
2 I also can use my bot (good4you)
3 I can send msessage from mybot to my id and received on my phone. (see attached "good4you" chat"
4 below command still failed (no file received on my id)
  _SendPhoto("513158325","C:\image.jpg")

bots on my id
=====
![add_bots](https://user-images.githubusercontent.com/37009382/44271910-f4fa9d00-a26d-11e8-84dc-00c8bbb0d7cf.gif)

my bot sent message to my id
=====
![mybotchat](https://user-images.githubusercontent.com/37009382/44272092-781bf300-a26e-11e8-9244-63273ae5f086.gif)



Q:  Should I upload my script and telegram.au3 for your checking?

**Comment by sergeyFlakon** [comment]
Yep, that will help, I'll take a look today/tomorrow
Thanks

**Comment by paynepeng** [comment]
1 attached is my script which download from github. I ran the tests\test.au3 (replace token/chatid with my own) 

2 there is an error for "telegram.au3" at line 618. I modified "," with ")". 

3 the test result as below 
=======
Test file for Telegram UDF by LinkOut. (https://github.com/xLinkOut)
This file need a valid ChatID of a Telegram User to send messages to, and a valid bot's token given by BotFather.\n
Insert this data in the source code
Initializing bot... True ...Done!
Who am I? Well...
Oh, yeah, my name is good4you, you can find me at @niceworldbot. For developers, my Telegram ID is 659601497. That's it!
Let's do some test:
Sending a simple text message. The function _SendMsg return the Message ID: 100
Now I'll forward the same message to you, with the message id saved before.Awesome. Now use the other _Send function to send photos, videos, documents and other. Each of this function return the FileID assigned by Telegram.
Sending photo...False ...Done!
Sending video...False ...Done!
Sending audio...False ...Done!
Sending documents...BQADBQADKwAD5cK4Vy80qugB8zkOAg ...Done!
Sending voice...False ...Done!
Sending sticker... ...Done! ( I don't put sample file into c:\  ,  so ignore this result)
Sending video note...False ...Done!
And also, send location and contact:
Sending location... True...Done! 
Sending contact... True... Done!
You can send a 'Chat Action', that mean the user see 'Bot is typing...' or 'Bot is sending a photo...'.
To use the custom keyboard, I wrote an useful function that contruct and encode the keyboard.You have to create an array e simply put in the text of your button. To line break, leave an array position empty.Example, try to pass this array $keyboard[4] = ['TopLeft','TopRight','','SecondRow'] to the _CreateKeyboard function, then send a message.In encoded format, the $keyboard look like {"keyboard":[["TopLeft","TopRight"],["SecondRow"]]}
Well, now I'll send this keyboard to you as this: _SendMsg($ChatID,'This is the text',Default,$markup)
_CreateKeyboard function accept two other boolean args, resize and one time keyboard, both false by default.
Well.. this is all folks! For the other method read the Telegram Documentation and the Telegram.au3 file, it's commented ;) and see the others example in the folder.
If you enjoy this UDF, star this repo on GitHub. This mean a lot for me. And if you want to donate me a coffe, there is a PayPal link in the ReadMe, I'll appreciate this. Bye

4 my script
=======
[myscript.zip](https://github.com/xLinkOut/telegram-udf-autoit/files/2298059/myscript.zip)

**Comment by paynepeng** [comment]
Did you try my script?   what could I do to speed up your analysis?

**Comment by xLinkOut** [comment]
Hey! I'm working on this issue right now. Soon more details...

**Comment by xLinkOut** [comment]
I've just pushed some changes in Test file. Clone this new version of the repository, try it (run as it is, insert only bot token and your chat id) and let me know.

**Comment by paynepeng** [comment]
downloaded and there are two errors about source code
1 telegram.au3 -- line 610 "$Path,"  => I modefied it as "$Path)"
2 tests\test.au3 -- line 25 warning: $MsgID: possibly used before declaration
3 run test.au3 failed, see below message  --- I make sure I insert correct chatid and token into code 
Test file for Telegram UDF by LinkOut. (https://github.com/xLinkOut)
This file need a valid ChatID of a Telegram User to send messages to, and a valid bot's token given by BotFather.\n
Insert this data in the source code
Ops! Error: reason may be invalid token, webhook active, internet connection...-- Ops! Error: reason may be invalid token, webhook active, internet connection..

note: I traced the error which cause by  _InitBot($Token) - call to _GetMe()
8/26 I found  _GetMe() send api command without token, see below
https://api.telegram.org/bot/getMe
it should be as below -
https://api.telegram.org/bot659601497:AAEZg7-gz0qrVCNfLTYjDGQG6oLK5h6fcaA/getMe

8/26 After recovered all code error, The test.au3 can be running complet.  following is report
Test file for Telegram UDF by LinkOut. (https://github.com/xLinkOut)
This file need a valid ChatID of a Telegram User to send messages to, and a valid bot's token given by BotFather.\n
Insert this data in the source code
Initializing bot... True
Who am I? Well...
Oh, yeah, my name is good4you, you can find me at @niceworldbot. For developers, my Telegram ID is 659601497. That's it!
Let's do some test:
	Sending a simple text message. The function _SendMsg return the Message ID: 122
	Now I'll forward the same message to you, with thedi message id saved before.False
	Awesome. Now use the other _Send function to send photos, videos, documents and other. Each of this function return the FileID assigned by Telegram.
!		Sending photo... False
!		Sending video... False
!		Sending audio... False
!		Sending documents... BQADBQADPwADxxYQVMEEhImE7gjoAg
!		Sending voice... False
!		Sending sticker... False
!		Sending video note... False
And also, send location and contact:
Sending location... True...Done! 
Sending contact... True... Done!
You can send a 'Chat Action', that mean the user see 'Bot is typing...' or 'Bot is sending a photo...'.
To use the custom keyboard, I wrote an useful function that contruct and encode the keyboard.You have to create an array and insert the text of your buttons. To line break, leave a position empty.Example, try to pass this array $keyboard[4] = ['TopLeft','TopRight','','SecondRow'] to the _CreateKeyboard function, then send a message.In encoded format, the $keyboard look like {"keyboard":[["TopLeft","TopRight"],["SecondRow"]]}
I'll send this keyboard to you as this: _SendMsg($ChatID,'This is the text',Default,$markup)
_CreateKeyboard function accept two other boolean args, resize and one time keyboard, both false by default.
Well.. this is all folks! For the other methods read the Telegram Documentation and the Telegram.au3 file, it's commented ;) and see the others example in the folder.
If you enjoy this UDF, star this repo on GitHub. This mean a lot for me. And if you want to donate me a coffe, there is a PayPal link in the ReadMe, I'll appreciate this. Bye

what my phone received
![test_result](https://user-images.githubusercontent.com/37009382/44624970-94cfbf00-a92f-11e8-9afa-73e85aa71336.gif)

**Comment by xLinkOut** [comment]
Ok, so:
+ Fixed `$Path, => $Path)`. Thanks.
+ Fixed `$MsgID` used before declaration.
+ Fixed an error in `_InitBot()` that recognize `_GetMe()` always as false. `If Not _GetMe()` => `If Not isArray(_GetMe())`.

I don't know why you don't receive other medias from the script. Have you cloned the new repository? With media folder under tests/?

I a few minute I'll send you a modified version of Telegram.au3, with some consolewrite debug, so I can read what Telegram send to you.

**Comment by xLinkOut** [comment]
Use this custom version of `Telegram.au3` and write here console output.
[debugTelegram.zip](https://github.com/xLinkOut/telegram-udf-autoit/files/2321510/debugTelegram.zip)

**Comment by paynepeng** [comment]
1 The downloaded files from github have media folder&files included. There is file upload issue at my side.
2 I tried to use "curl" instead,  The file upload functions success.(photo/video/audio/voice/videonote/sticker)
3 The debug version of telegram downloaded, I will try it soon
thanks for your help!

**Comment by paynepeng** [comment]
debug telegram.au3  test report
===========
Test file for Telegram UDF by LinkOut. (https://github.com/xLinkOut)
This file need a valid ChatID of a Telegram User to send messages to, and a valid bot's token given by BotFather.
Insert this data in the source code.
Initializing bot... True
Who am I?
Oh, yeah, my name is good4you, you can find me at @niceworldbot. For developers, my Telegram ID is 659601497. That's it!
Let's do some test:
	Sending a simple text message. The function _SendMsg return the Message ID: 161
	Now I'll forward the same message to you, with the message id saved before: 162
	Awesome. Now use the other _Send function to send photos, videos, documents and other. Each of this function return the FileID assigned by Telegram.


!		Sending photo... False


!		Sending video... False


!		Sending audio... False

{"ok":true,"result":{"message_id":163,"from":{"id":659601497,"is_bot":true,"first_name":"good4you","username":"niceworldbot"},"chat":{"id":513158325,"first_name":"\u58eb\u6587","last_name":"\u5f6d","username":"ppeng2018","type":"private"},"date":1535291442,"document":{"file_name":"text.txt","mime_type":"text/plain","file_id":"BQADBQADLgADWR4YVOEii_bDMGpCAg","file_size":27},"caption":"This is a document."}}
!		Sending documents... BQADBQADLgADWR4YVOEii_bDMGpCAg


!		Sending voice... False


!		Sending sticker... False


!		Sending video note... False
And also, send location and contact:
Sending location... True
Sending contact... True
You can send a 'Chat Action', that mean the user see 'Bot is typing...' or 'Bot is sending a photo...'.
To use the custom keyboard, I wrote an useful function that contruct and encode the keyboard.You have to create an array and insert the text of your buttons. To line break, leave a position empty.Example, try to pass this array $keyboard[4] = ['TopLeft','TopRight','','SecondRow'] to the _CreateKeyboard function, then send a message.In encoded format, the $keyboard look like {"keyboard":[["TopLeft","TopRight"],["SecondRow"]]}
I'll send this keyboard to you as this: _SendMsg($ChatID,'This is the text',Default,$markup)
_CreateKeyboard function accept two other boolean args, resize and one time keyboard, both false by default.
Well.. this is all folks! For the other methods read the Telegram Documentation and the Telegram.au3 file, it's commented ;) and see the others example in the folder.
If you enjoy this UDF, star this repo on GitHub. This mean a lot for me. And if you want to donate me a coffe, there is a PayPal link in the ReadMe, I'll appreciate this. Bye <3+>

**Comment by paynepeng** [comment]
Here is my compiled test.au3 with debug telegram.au3.  
I ran it on two win7 pc but got upload files fail result. 
please download &run it at your side to see if it success.

[tests.zip](https://github.com/xLinkOut/telegram-udf-autoit/files/2321564/tests.zip)

**Comment by xLinkOut** [comment]
Ehy! Sorry for this looong silence! BUT, I've updated test file, try it now if you still have problem with sendmedia functions.

**Comment by paynepeng** [comment]
many thanks for your reply.  I re-download all package from github and tried. The bad news is "test failed" as before. please see following test report. 

test report
==========
Test file for Telegram UDF by LinkOut. (https://github.com/xLinkOut)
This file need a valid ChatID of a Telegram User to send messages to and a valid bot token given by BotFather.
Insert this data in the source code.

! Initializing bot... True

Who am I? Oh, yeah, my name is 自由聯盟, you can find me at @niceworldbot. For developers, my Telegram ID is 659601497
Let's do some test:
	Sending a simple text message. The function _SendMsg return the Message ID: 匸?557
	Now I'll forward the same message to you, with the message id saved before: 558
	Awesome. Use the other _Send functions to send photos, videos, documents. Each function return the FileID assigned by Telegram.
!		Sending photo: False
!		Sending video: False
!		Sending audio: False
!		Sending documents: BQADBQADIwADq7sYVbgecyaNvqOjAg
!		Sending voice: False
!		Sending sticker: False
!		Sending video note: False
!		Sending location: True
!		Sending contact: True

You can send a 'Chat Action', that mean the user see 'Bot is typing...' or 'Bot is sending a photo...'.

To use a custom keyboard, there is an useful function that contruct and encode the keyboard itself.
You have to create an array and insert the text of your buttons. To line break, leave a position empty. 
Example, try to pass this array $keyboard[4] = ['TopLeft','TopRight','','SecondRow'] to the _CreateKeyboard function, then send the message.

In encoded format, the $keyboard look like {"keyboard":[["TopLeft","TopRight"],["SecondRow"]]}
I'll send this keyboard to you as this: _SendMsg($ChatID,'Hey! Choose one:',Default,$markup)
_CreateKeyboard function accept two other boolean args, resize and one time keyboard, both false by default.

This is all folks! For all the other methods read the Telegram Documentation and the Telegram.au3 file, it's commented. You can find some examples in the example folder.
Don't forget to ì star this repo on GitHub, this mean a lot for me.o+>22:17:23 AutoIt3.exe ended.rc:0
+>22:17:23 AutoIt3Wrapper Finished.
>Exit code: 0    Time: 212.7

**Comment by xLinkOut** [comment]
Mmh.. I think that there is upload issue by your side. Maybe you can try with different isp? Or with internet connection of your friend?

**Comment by sergeyFlakon** [comment]
You can check it without changing ISP, just use VPN or proxy for your bot (proxifier / proxycap)

**Comment by xLinkOut** [comment]
Closed due to inactivity.
